stages:
  - deques
  - autocomplete
  - minpq
  - seamfinding

test-deques:
  stage: deques
  rules:
    - changes:
        - src/main/java/BrowserHistory.java
        - src/{main,test}/java/deques/**/*.java
  script: ./gradlew --warning-mode=all test --tests "deques.*"

test-autocomplete:
  stage: autocomplete
  rules:
    - changes:
        - src/main/java/CitySearch.java
        - src/main/java/DNASearch.java
        - src/{main,test}/java/autocomplete/**/*.java
  script: ./gradlew --warning-mode=all test --tests "autocomplete.*"

test-minpq:
  stage: minpq
  rules:
    - changes:
        - src/main/java/ReportAnalyzer.java
        - src/{main,test}/java/minpq/**/*.java
  script: ./gradlew --warning-mode=all test --tests "minpq.*"

test-seamfinding:
  stage: seamfinding
  rules:
    - changes:
        - src/main/java/SeamCarver.java
        - src/main/java/graphs/**/*.java
        - src/{main,test}/java/seamfinding/**/*.java
  script: ./gradlew --warning-mode=all test --tests "seamfinding.*"
